### ISSUE TITLE
[나연] 게시물 등록 및 조회 API 구현 

### ISSUE THREAD

**Issue by hellonayeon** [yum-yum-trend/backend#20]
* 객체 관계 매핑
* 내용 입력받아 데이터베이스에 저장

**Comment by hellonayeon** [comment]
* 매핑관계 수정
  * 객체 자체가 아니라 `userId` 만 갖도록 수정할 예정

* `.yml` 파일 수정
  * `application.yml`으로 통합할 수 있도록 계층구조 수정할 예정

**Comment by hellonayeon** [comment]
프로젝트 폴더 `/src/main/resources` 하위에 `aws.yml` 파일 추가해주세요!
@KKHoon210417 @profoundsea25 @HWON0720 

**aws.yml**
```yml
cloud:
  aws:
    credentials:
      accessKey: IAM AWS_ACCESS_KEY_ID
      secretKey: IAM AWS_SECRET_ACCESS_KEY
    s3:
      bucket: BUCKETNAME
    region:
      static: ap-northeast-2
    stack:
      auto: false
```

`yml` 파일 구조가 변경되면, 반영사항 다시 말씀드리겠습니다 ~
