### ISSUE TITLE
YML 파일 설정

### ISSUE THREAD

**Issue by hellonayeon** [yum-yum-trend/backend#26]
**기존의 `application.properties` 파일 삭제
`src/main/resources` 폴더 하위에 만들어주시면 됩니다!

**application.yml**
```yml
spring:
  profiles:
    include:
      - aws
      - credentials
  h2:
    console:
      enabled: false
  datasource:
    driverClassName: org.h2.Driver
    url: [JDBC URL] # example: jdbc:h2:./yum-yum-trend-db;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
jwt:
  secret: javainuse
```

**application-aws.yml**
```yml
cloud:
  aws:
    s3:
      bucket: [BUCKETNAME]
      folder:
        articleImagesFolder: article-images/
    region:
      static: ap-northeast-2
    stack:
      auto: false
```

**application-credentials.yml**
```yml
cloud:
  aws:
    credentials:
      accessKey: [AWS_ACCESS_KEY_ID]
      secretKey: [AWS_SECRET_ACCESS_KEY]
```
