### ISSUE TITLE
EC2 데이터베이스 연결을 위한 프로젝트 설정

### ISSUE THREAD

**Issue by hellonayeon** [yum-yum-trend/backend#47]
1. **`application-db.yml` 파일 추가**
2. **`application.yml`** 에 기존에 작성되어있던 `h2` `datasource` 주석 처리
3. `spring > profiles > include` 에 `db` 추가

**application-db.yml**
```yml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://[IP주소]:3306/[데이터베이스명]?serverTimezone=UTC&characterEncoding=UTF-8
    username: [사용자이름]
    password: [비밀번호]
```

**application.yml**
```yml
spring:
  profiles:
    include:
      - db
      - aws
      - credentials
#  h2:
#    console:
#      enabled: 
#  datasource:
#    driverClassName: 
#    url: 
#    username: 
#    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: false

logging:
  level:
    org:
      hibernate:
        SQL: error # debug
        type:
          descriptor:
            sql: trace
jwt:
  secret: javainuse
```
